apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: xotomicro-front-hook-system
  name: xotomicro-front-hook-system
spec:
  ports:
    - name: "7076"
      port: 7076
      targetPort: 80
  selector:
    io.kompose.service: xotomicro-front-hook-system
status:
  loadBalancer: {}
