apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: xotomicro-front-shell-system
  name: xotomicro-front-shell-system
spec:
  ports:
    - name: "7070"
      port: 7070
      targetPort: 80
  selector:
    io.kompose.service: xotomicro-front-shell-system
status:
  loadBalancer: {}
