git submodule add https://github.com/xotomicro/xotomicro-front-hook-system.git ./packages/system/xotomicro-front-hook-system
git submodule add https://github.com/xotomicro/xotomicro-front-shell-system.git ./packages/system/xotomicro-front-shell-system
git submodule add https://github.com/xotomicro/xotomicro-front-auth-service.git ./packages/service/xotomicro-front-auth-service
git submodule add https://github.com/xotomicro/xotomicro-front-event-service.git ./packages/service/xotomicro-front-event-service
git submodule add https://github.com/xotomicro/xotomicro-front-order-service.git ./packages/service/xotomicro-front-order-service
git submodule add https://github.com/xotomicro/xotomicro-front-product-service.git ./packages/service/xotomicro-front-product-service
git submodule add https://github.com/xotomicro/xotomicro-front-user-service.git ./packages/service/xotomicro-front-user-service
git submodule add https://github.com/xotomicro/xotomicro-front-design-registry.git ./registries/xotomicro-front-design-registry
git submodule add https://github.com/xotomicro/xotomicro-front-utility-registry.git ./registries/xotomicro-front-utility-registry
git submodule add https://github.com/xotomicro/xotomicro-front-common-registry.git ./registries/xotomicro-front-common-registry
